name: Zip

on:
  workflow_dispatch:
  push:
    tags: "v*.*.*"

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      
      - run: mkdir dist

      - name: Git Archive
        working-directory: dist
        run: git archive ${GITHUB_REF_NAME} -o unipack_resource_${GITHUB_REF_NAME}.zip

      - name: Tree
        run: |
          pwd
          tree

      - name: Upload a Artifact
        uses: actions/upload-artifact@v4.6.2
        with: 
          path: dist/