name: Zip

on:
  workflow_dispatch:
  push:
    tags: "v*.*.*"

jobs:
  zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - run: mkdir dist

      - name: Git Archive
        working-directory: dist
        run: |
          echo ${GITHUB_REF_NAME}
          git archive "${GITHUB_REF_NAME}" -o unipack_resource_${GITHUB_REF_NAME}.zip

      - name: Tree
        run: |
          pwd
          tree

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: dist/*
          token: ${{ secrets.GITHUB_TOKEN }}
